#!/bin/bash

# Last update 2020/04/09 by pavroo

DEVCHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

if [ -f /sys/firmware/efi/efivars/SecureBoot-* ]; then
	echo " * Installing Secure Boot support..."
	mv $DEVCHROOT/usr/sbin/grub-probe $DEVCHROOT/usr/sbin/grub-probe.bak
	echo "exit 0" > $DEVCHROOT/usr/sbin/grub-probe
	chmod +x $DEVCHROOT/usr/sbin/grub-probe
	mkdir -p $DEVCHROOT/debs
	if [ -d /lib/live/mount/medium/offlinesigned ]; then
		cp /lib/live/mount/medium/offlinesigned/* $DEVCHROOT/debs/
	else
		cp /run/live/medium/offlinesigned/* $DEVCHROOT/debs/
	fi	
cat > $DEVCHROOT/tmp/signed-install << FOO
#!/bin/bash
cd debs
dpkg -i *.deb
cd ..
FOO
	chmod +x $DEVCHROOT/tmp/signed-install
	chroot $DEVCHROOT /tmp/signed-install
	rm -f $DEVCHROOT/tmp/signed-install
	rm -rf $DEVCHROOT/debs
	if [ ! -d "$DEVCHROOT/boot/efi/EFI/debian" ]; then
		mkdir -p $DEVCHROOT/boot/efi/EFI/debian
		cp $DEVCHROOT/boot/efi/EFI/sparky/* $DEVCHROOT/boot/efi/EFI/debian/
	fi
	rm -f $DEVCHROOT/usr/sbin/grub-probe
	mv $DEVCHROOT/usr/sbin/grub-probe.bak $DEVCHROOT/usr/sbin/grub-probe
fi
